### ISSUE TITLE
Well known rug-puller: Mario

### ISSUE THREAD

**Issue by AgentK77** [oceanprotocol/list-purgatory#27]
Asset :
did:op:D4DD7F5A182dDAA45D0ae2976FF7b71C69aE0536

Wallet:
0x02eFA471d2ECE1dd4Fa317abB6E3278CB01F6327

Hash:
In
0x762430689a11f65b8a8c3b91c788f1ab4c98c568cc2099f4c3a48fbaaff5ec66
Out
0x17b7b4da17a7f531f2ef14775f870c1cd82bb9078704d1df766f2207ad50c587

**Comment by kaimeinke** [comment]
I totally agree on this one. A confirmed bad actor it is. 👍

**Comment by AgentK77** [comment]
Funds are now transferred to this address:
[https://etherscan.io/address/0x9826754e29333e52eaecebcb05dd3be4dd7ac899#tokentxns](url)

Hash:
[https://etherscan.io/tx/0xcdf49130f73da30d3b1ba1ac72aea5549903cb95828e0e0ba8a517aeebf309f2](url)
Via:
[https://etherscan.io/tx/0x4c2926965f6d6a46f5c36516ab05f697f1a4814c01e91eaceb7f1a34657c9c3d](url)

**Comment by kaimeinke** [comment]
Created https://github.com/oceanprotocol/list-purgatory/pull/28 to include the assets of this actor into purgatory `list-assets.json`

**Comment by kaimeinke** [comment]
I guess this issue can be closed now with the latest merged pull requests. @AgentK77

**Comment by kremalicious** [comment]
done by #28
