### ISSUE TITLE
Email dataset

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/list-purgatory#30]
Good candidate for purgatory:  https://market.oceanprotocol.com/asset/did:op:9bc4Cb2FBbFE520953701Dcc6F6653Ac735a562c

**Comment by kaimeinke** [comment]
I totally agree and this has been discussed on Telegram as well. It is most likely a violation and I thought somebody already made pull request for it to be honest. If it is useful, I would make one, but inquire about the publisher on Telegram first.

**Comment by trentmc** [comment]
This was handled 12 days ago.
