### ISSUE TITLE
Update rules to include matic/polygon

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/list-purgatory#34]
Update the purgatory rules to account for the following : 

> Note: Only republish datatokens from Ethereum mainnet here if there is <1000 OCEAN liquidity in the original pool. Doing otherwise will lead to purgatory

**Comment by trentmc** [comment]
Done in 
https://github.com/oceanprotocol/list-purgatory/commit/71403fd9222b824c708fd1859fab475383ffbce1
