### ISSUE TITLE
Add polygon test asset to purgatory

### ISSUE THREAD

**Issue by MantisClone** [oceanprotocol/list-purgatory#44]
Please add https://market.oceanprotocol.com/asset/did:op:2357C32D8C68514D4186D0e193836156a133F0f3 to the purgatory. I created it while working on https://github.com/oceanprotocol/ocean.py/issues/307

**Comment by mihaisc** [comment]
This is not a valid bug report. Please create a pull request, here is a quick example https://github.com/oceanprotocol/list-purgatory/pull/43

**Comment by MantisClone** [comment]
@mihaisc Thanks for the guidance! 

Per your request, I have created PR #47. I think it would have made sense to keep this issue open until the PR is merged, but I've linked the PR to this issue nonetheless.
