### ISSUE TITLE
Add chain to the schema

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/list-purgatory#46]
I suggest to add chain id or chain name. While testing aquarius i realized that comparing the number of assets in purgatory was inaccurate because we have assets on main and polygon. By having this information it will be easier to check how many assets are in purgatory on each chain

{
  "did": "did:op:0000",
  "reason": "stolen data",
  "chainId" : "1" OR "chainName" : "ethereum/polygon"
},

**Comment by mihaisc** [comment]
On a second note, this might not be as useful now that we have multichain aqua

**Comment by trentmc** [comment]
> On a second note, this might not be as useful now that we have multichain aqua

How does multichain aqua solve this specifically? 

Aqua is supposed to be a cache, not a ground-zero source of truth.  So wouldn't we still want chainid specified here?

@mihaisc

**Comment by mihaisc** [comment]
It's not usefull for what i was thinking at that time (checking if aqua was setting the `isPurgatory` field correctly). But you are right, this will have value in the future, so this is a valid issue.

**Comment by trentmc** [comment]
Thanks.

Why do you see this as "value in the future" versus "is an issue right now" ? 

Specifically: isn't it ambiguous if I put an asset into purgatory and don't specify chain id? (ie an error). Perhaps there is an answer: the did resolves to include chain id?

**Comment by mihaisc** [comment]
I think there might be some misunderstandings. By `a valid issue` i mean a valid github issue, not that we have a problem right now.   I can see it useful because right now you don't know on what chain the asset is, maybe it's something in the description. But maybe we can get some quick statistics  (a quick grouping to see what we have in purgatory, without using aquarius), or maybe other uses. 
This was my point, technically we don't need it right now, the stack work fine without it,. But maybe in the future this has some value

**Comment by trentmc** [comment]
> technically we don't need it right now, the stack work fine without it

How does it work fine right now? Does it just filter out all assets matching the did across all chains? (If yes then that's probably fine, and frankly we could probably close the ticket until there's actually a problem:)

**Comment by mihaisc** [comment]
> Does it just filter out all assets matching the did across all chains? 

Correct. We can close this.

**Comment by trentmc** [comment]
👍
