### ISSUE TITLE
for list of accounts, should e.g. only checksummed addresses be mandated?

### ISSUE THREAD

**Issue by TimDaub** [oceanprotocol/list-purgatory#50]
According to EIP55, there are two types of Ethereum EOAs:

- lowercase: https://etherscan.io/address/0x3764fee26b0d428f7a77046a07ff6777cd64e7f2
- checksum: https://etherscan.io/address/0x3764Fee26B0D428f7A77046A07Ff6777CD64E7F2

For list-purgatory, a common use case is to "check if an address is banned", by e.g. using GitHub search: https://github.com/oceanprotocol/list-purgatory/search?q=0x3764fee26b0d428f7a77046a07ff6777cd64e7f2

Consider the following checksummed address in list-purgatory: 0xC247C2574e5C22B75410FCa7b8FE360dbd2f9e62

Now, let's search for its lowercased pendant: 0xc247c2574e5c22b75410fca7b8fe360dbd2f9e62
GitHub search finds it as it's ignoring case: https://github.com/oceanprotocol/list-purgatory/search?q=0xc247c2574e5c22b75410fca7b8fe360dbd2f9e62

However, any program that uses list-purgatory to filter using an equal operator (not ignoring case) must currently do the following:

- either lower or checksum all addresses before doing a comparison on equality.

To make handling these addresses safer, I hence propose that there's a continuous integration script running on this repository before e.g. a PR can be merged that checks if a submitted address has been correctly checksummed according to EIP55.

**Comment by trentmc** [comment]
> To make handling these addresses safer ...

By safer, I assume you mean "less error-prone"? @TimDaub 

There are at least two options:

1. continuous integration .. that checks if a submitted address has been correctly checksummed  (Tim's proposal)
2. add to README: "ensure to either lower or checksum all addresses before doing a comparison on equality."

(1) takes more time, but not huge. (2) is super simple to do here, but could get missed by devs using it.

Also worth noting: there is a small # devs using this data right now. With those devs we can iterate closely (hi Tim!). So priority should be calibrated against other target tasks.

**Comment by TimDaub** [comment]
> By safer, I assume you mean "less error-prone"? @TimDaub

I'm referring to the [safety property](https://en.wikipedia.org/wiki/Safety_property). As in "something bad will never happen."

I've done both of your suggestions now. See https://github.com/oceanprotocol/list-purgatory/pull/51

**Comment by trentmc** [comment]
Hi @TimDaub thanks very much for doing the PR. Given that reviews by others was moving slowly, I accepted the PR and merged. 

Then I realized that you still had an open question:

> Oh, I just saw that there's a check with Travis CI here. I see two options:
> (1) I move the checks from Travis to GH Actions (should be straight forward)
> (2) I move from GH Actions to Travis
> Preferences? 

Given the open question, which the PR did not address, I reverted the PR. https://github.com/oceanprotocol/list-purgatory/commit/76760d68bdb0351c1c925f3fee8630fbed609dc3 then https://github.com/oceanprotocol/list-purgatory/commit/3930230593bc2ee9b0064309dd673a65a658aaf6

But I'd still like to move this forward, of course.

First, Tim, here's the answer to your Q: our preference is (1). That is, use GH actions.

As a next step - Tim could you revive the PR and include GH actions, please?

Thanks!
